name: Push File

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev, stage and main branch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: '${{github.workspace}}/docs/2RG.md'
        src_branch: '${{ github.ref_name }}'
        dst_path: assets
        dst_owner: Fiserv
        dst_repo_name: tenants-data
        dst_branch: '${{ github.ref_name }}'
        email: 'abhishek.singh3@fiserv.com'
        username: 'asingh2023'
        commit_message: 'pushing zip file remotely'         
       