name: Push File

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev, stage and main branch

name: Copy File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: Fiserv/remote-actions-v1
          ref: develop

      - name: Upload file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: file-to-copy
          path: ${{github.workspace}}/assets/${{ github.event.repository.name }}_postman.zip
          
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: Fiserv/tenants-data
          ref: develop

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: file-to-copy
          path: ${{github.workspace}}/assets/${{ github.event.repository.name }}_postman.zip

      - name: Upload file to target folder
        uses: actions/upload-file@v2
        with:
          repository: Fiserv/tenants-data
          path: path/to/download/file
          target-path: Fiserv/tenants-data/assets
# jobs:
#   copy-file:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Pushing tenant postmant collection zip file remotely into teanants-data repository.
#       uses: nkoppel/push-files-to-another-repository@1.1.1
#       env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}     
#       with:
#         source_file: '${{github.workspace}}/assets/${{ github.event.repository.name }}_postman.zip'
#         destination-username: 'Fiserv'
#         destination-repository: 'tenants-data'
#         destination-directory: 'assets'
#         destination-branch: '${{ github.ref_name }}'
#         commit-email: 'abhishek.singh3@fiserv.com'
#         commit-username: 'asingh2023'
#         commit_message: 'pushing zip file remotely'
