name:  Test Upload Files

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
  
jobs:
  copy-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: 'Fiserv/remote-actions-v1'
          ref: 'develop'

      # - name: Extract zip file
      #   run: |
      #     unzip -P ${{ secrets.SOURCE_ZIP_PASSWORD }} {source_path}

      - name: Configure git credentials
        run: |
          git config --global user.name "asingh2023"
          git config --global user.email "abhishek.singh3@fiserv.com"

      - name: Clone destination repo
        uses: actions/checkout@v2
        with:
          repository: 'Fiserv/tenants-data'
          token: ${{ secrets.ZIP_GENERATOR_ACTION }}
          path: Fiserv/tenants-data/assets

      - name: Copy zip file to destination repo
        run: |
          cp ${{github.workspace}}/assets/${{ github.event.repository.name }}_postman.zip Fiserv/tenants-data/assets

      - name: Commit and push changes
        run: |
          cd Fiserv/tenants-data
          git add .
          git commit -m "Copy zip file from ${{ github.event.repository.name }} to Fiserv/tenants-data"
          git push -u ${{ secrets.SECRET_KEY }}
        env:
          SECRET_KEY: ${{ secrets.ACTION_SECRET }}           
 