name: Tenant Validator
on:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev, stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]
   
jobs:
  api-validator: 
    uses: Fiserv/remote-actions/.github/workflows/github-yaml-validator.yaml@develop
    if: ${{ (github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main') }}  
  # docs-validator: 
  #   uses: Fiserv/remote-actions/.github/workflows/github-md-validator.yaml@develop
  #   if: ${{ (github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main') }}    
  tenant-config-validator: 
    uses: Fiserv/remote-actions/.github/workflows/github-tenant-config-validator.yaml@develop
    if: ${{ (github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main') }}     
  api-zip-generator:
    needs: api-validator
    uses: Fiserv/remote-actions/.github/workflows/github-zip-generator.yaml@develop
    if: ${{ (github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main') }}     
